package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// ShopAvailability controls how many replicas the Shop app is deployed with.
// +kubebuilder:validation:Enum=standard;high
type ShopAvailability string

const (
	// ShopAvailabilityStandard deploys 2 replicas.
	ShopAvailabilityStandard ShopAvailability = "standard"
	// ShopAvailabilityHigh deploys 3 replicas.
	ShopAvailabilityHigh ShopAvailability = "high"
)

// ShopDatabaseKind selects which database (and which operator provisions it) backs the shop.
// +kubebuilder:validation:Enum=standard;light
type ShopDatabaseKind string

const (
	// ShopDatabaseKindStandard provisions PostgreSQL via CNPG (https://cloudnative-pg.io/).
	ShopDatabaseKindStandard ShopDatabaseKind = "standard"
	// ShopDatabaseKindLight provisions Redis (or another lightweight store) via its own operator.
	ShopDatabaseKindLight ShopDatabaseKind = "light"
)

// ShopSpec defines the desired state of Shop.
type ShopSpec struct {
	// Name is the shop's display name.
	// +kubebuilder:validation:MinLength=1
	Name string `json:"name"`

	// Availability controls replica count: standard=2, high=3.
	// +kubebuilder:default=standard
	Availability ShopAvailability `json:"availability,omitempty"`

	// WalletAddress is the on-chain address that receives this shop's customer payments.
	// +kubebuilder:validation:MinLength=1
	WalletAddress string `json:"walletAddress"`

	// DatabaseKind selects the shop's database: standard=PostgreSQL (CNPG), light=Redis.
	// +kubebuilder:default=standard
	DatabaseKind ShopDatabaseKind `json:"databaseKind,omitempty"`
}

// ShopPhase is a coarse summary of a Shop's reconciliation state.
type ShopPhase string

const (
	ShopPhasePending ShopPhase = "Pending"
	ShopPhaseReady   ShopPhase = "Ready"
	ShopPhaseFailed  ShopPhase = "Failed"
)

// ShopStatus defines the observed state of Shop.
// TODO: populated by the (not yet implemented) Shop controller — see
// internal/controller/shop_controller.go. Until then this is always empty on freshly
// created resources, which is expected: a CRD's API server accepts and stores spec/status
// regardless of whether any controller is running to reconcile it.
type ShopStatus struct {
	// +optional
	Phase ShopPhase `json:"phase,omitempty"`

	// +optional
	Conditions []metav1.Condition `json:"conditions,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Availability",type=string,JSONPath=`.spec.availability`
// +kubebuilder:printcolumn:name="Database",type=string,JSONPath=`.spec.databaseKind`
// +kubebuilder:printcolumn:name="Phase",type=string,JSONPath=`.status.phase`

// Shop is the Schema for the shops API.
type Shop struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ShopSpec   `json:"spec,omitempty"`
	Status ShopStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ShopList contains a list of Shop.
type ShopList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Shop `json:"items"`
}

func init() {
	SchemeBuilder.Register(&Shop{}, &ShopList{})
}

// The methods below are normally generated by `controller-gen object` (via `make
// generate`) from the +kubebuilder:object markers above. Hand-written here since Go/
// kubebuilder aren't installed in the scaffolding environment — regenerate and replace
// once the toolchain is available.

func (in *Shop) DeepCopyInto(out *Shop) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

func (in *Shop) DeepCopy() *Shop {
	if in == nil {
		return nil
	}
	out := new(Shop)
	in.DeepCopyInto(out)
	return out
}

func (in *Shop) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ShopStatus) DeepCopyInto(out *ShopStatus) {
	*out = *in
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
}

func (in *ShopList) DeepCopyInto(out *ShopList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]Shop, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *ShopList) DeepCopy() *ShopList {
	if in == nil {
		return nil
	}
	out := new(ShopList)
	in.DeepCopyInto(out)
	return out
}

func (in *ShopList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
