---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  - services
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.shophub.io
  resources:
  - discordchannels
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.shophub.io
  resources:
  - discordchannels/status
  - shops/status
  - wallets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps.shophub.io
  resources:
  - shops
  - wallets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - alertmanagerconfigs
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - postgresql.cnpg.io
  resources:
  - clusters
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redis.redis.opstreelabs.in
  resources:
  - redis
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
